### ISSUE TITLE
Quantity of items ordered is not set correctly

### ISSUE THREAD

**Issue by SteveFromAccounting** [Affirm/Magento_Affirm#48]
When I create a new order, it shows up in the Affirm Merchant dashboard with the incorrect quantity set (it is always `1`). This seems to be because of the following line:

https://github.com/Affirm/Magento_Affirm/blob/master/extension/app/code/community/Affirm/Affirm/controllers/PaymentController.php#L312

Despite the name of the variable, `$orderItem` is actually a `Mage_Sales_Model_Quote_Item`, NOT a `Mage_Sales_Model_Order_Item`, because `$quote->getAllVisibleItems()` returns an array of quote items. A quote item does not have the attribute of `qty_ordered` (while an order item does), and so that call will always return `null`. 

That said, let me know if the above is incorrect and if it's something I'm doing incorrectly on my end. Thanks!

**Comment by nandadubey** [comment]
Thanks for bringing this to our attention, we will keep you posted as we look into this issue.

**Comment by diptib10** [comment]
Fixed in version 3.6.1.
