### ISSUE TITLE
3.6.1 package still Shows 3.6.0

### ISSUE THREAD

**Issue by cdbessig** [Affirm/Magento_Affirm#62]
I downloaded the latest release file from github, specifically Affirm_Affirm-3.6.1.tgz

Inside this tgz file is the extension/app/code/community/Affirm/Affirm/etc/config.xml

This file shows:

```
<modules>
        <Affirm_Affirm>
            <version>3.6.0</version>
        </Affirm_Affirm>
    </modules>
```

The expected result is that this file would have:

```
<modules>
        <Affirm_Affirm>
            <version>3.6.1</version>
        </Affirm_Affirm>
    </modules>
```

The source repo on gitlab when I forked does have the 3.6.1 in the file.  Perhaps this build process failed or is the old version of the module?

**Comment by kkong87** [comment]
Fixed in 3.6.2
